spring.application.name=neo

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=redis-cache
spring.data.redis.port=6379

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}

app.grok.model.name=llama-3.3-70b-versatile
app.gemini.model.name=gemini-2.5-flash-lite
app.gemini.model.name2=gemini-2.5-flash

app.grok.api.key=${GROK_API_KEY}
app.gemini.api.key=${GEMINI_API_KEY}

encryption.key=${ENCRYPTION_KEY}

# ===== Resilience4j Circuit Breaker =====
resilience4j.circuitbreaker.instances.ai-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ai-service.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.ai-service.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.ai-service.permitted-number-of-calls-in-half-open-state=1
resilience4j.circuitbreaker.instances.ai-service.sliding-window-size=5
resilience4j.circuitbreaker.instances.ai-service.sliding-window-type=count_based
resilience4j.circuitbreaker.instances.ai-service.register-health-indicator=false

# ===== Retry Configuration =====
resilience4j.retry.instances.ai-service.max-attempts=1


# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Frontend URL for reset links
app.frontend.url=https://dbsight-reset-password.vercel.app/
